### ISSUE TITLE
Rename user_id to signin_name

### ISSUE THREAD

**Issue by kyoshizaki** [lepo-project/lepo#3]
## Background
In some tables, column name user_id is used for User.id store. In this situation, column name User.user_id for signin name is misleading, so rename user_id to something else.

## ToDo
- [x] Decide new column name
  - **signin_name**
    - The meaning is easy to understand, no ambiguity.
    - For UI display, it can be shown with other word like "User ID" by using language file 
  - Other candidates (NOT used)
    - signinname: column name of multiple words are separated by _ in principle
    - user_name: for developer, User.signin_name is more easy to understand than User.user_name
- [x] Create migration file to replace column_name and execute it
- [x] Refactor code for column_name replace
- [x] Refactor test code for column_name replace
- [x] Confirm that other user's signin_name is not displayed to learners
  - signin_name should be displayed for course staffs and system staffs

**Comment by kyoshizaki** [comment]
Renamed!
